env:
  node: true

rules:
  no-multiple-empty-lines:
    - error
    - max: 1
  no-var:
    - error
  no-console:
    - error
    - allow:
      - warn
      - error
      - info
  arrow-parens:
    - error
    - always
  js-quotes:
    - error
    - prefer-double
